from pymongo import MongoClient, UpdateOne
import pandas as pd
import re

# Function to get data from Mongo

def get_dataframe_from_mongodb(collection_name, database_name, query={}):

    print(f"Fetching data from {database_name} : {collection_name}")
    client = MongoClient(f"mongodb+srv://rpdprocorpo:iyiawsSCfCsuAzOb@cluster0.lu6ce.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0")
    db = client[database_name]
    collection = db[collection_name]

    data = list(collection.find(query))

    if data:
        dataframe = pd.DataFrame(data)
        if '_id' in dataframe.columns:
            dataframe = dataframe.drop(columns=['_id'])
    else:
        dataframe = pd.DataFrame()

    print(f"Fetched {len(dataframe)} records from {database_name} : {collection_name}")
    return dataframe

# Function to extract the informations at the quote_itens
def extract_quote_items(row,df):
    items = []
    # Ajustando a regex para capturar corretamente todos os elementos
    for item in row['quote_items'].split(';'):
        item = item.strip() # TIRA SPACE
        if item:
            match = re.match(r'^(.*) \(Qty:\s*(\d+),\s*Amount:\s*(\d+),\s*discountAmount:\s*(\d+)\)', item)

            # See if it matched correctly
            if match:
                item_name = match.group(1)     # Nome do item
                qty = match.group(2)            # Quantidade
                amount = match.group(3)         # Valor (Amount)
                discount_amount = match.group(4) # Desconto

                # # Debugging - print the matched values
                # print("Matched:", item_name, qty, amount, discount_amount)

                items.append({
                    'item_name': item_name,
                    'quantity': int(qty),
                    'item-amount': int(amount),               # Convertendo para inteiro
                    'discount_amount': int(discount_amount), # Convertendo para inteiro
                    **{col: row[col] for col in df.columns if col != 'quote_items'}
                })

    return items

     # function that calls the treated updated dataframe

def treating_values(billcharges_df):

  # Dropping dulicates from quote_ID because there is all i need in quote_items:
  billcharges_df.drop_duplicates(subset=['quote_id'],keep='first', inplace=True)

  # Aplicar a função para cada linha do DataFrame
  rows = []
  for _, row in billcharges_df.iterrows():
      extracted_items = extract_quote_items(row,billcharges_df)
      rows.extend(extracted_items)

  # Criar um novo DataFrame com os dados extraídos
  new_df = pd.DataFrame(rows)

  #chosing the columns that i will use
  columns = ['customer_id', 'quote_id','date', 'store_name', 'item_name', 'quantity',
            'item-amount','discount_amount', 'payment_method','installments','total_amount','is_paid',
            'status']

  new_df = new_df[columns]

  #renaming these columns
  new_df.rename(columns={'customer_id': 'ID CLIENTE','quote_id':'ID ORÇAMENTO','store_name': 'UNIDADE',
                        'item_name' : "PROCEDIMENTO",'quantity':'QUANTIDADE','item-amount':'VALOR TABELA',
                        'discount_amount':'DISCONTO ITEM','payment_method': 'FORMA DE PAGAMENTO','installments':'PARCELAS',
                        'is_paid':'PAGO?','total_amount' : 'TOTAL DO ORÇAMENTO',"date" : "DATA","status" : "STATUS" }, inplace=True)

  # 
  new_df = new_df.loc[new_df["STATUS"] == "completed"]
  #bringing all dictionaries for the code
  custos_dict, Sales_dic, Appointments_dic, duration_dic, Month_dic = bring_dictionaries()

  #Maapping all the information from dictionaries:
  new_df["PROCEDIMENTO PADRONIZADO"] = new_df["PROCEDIMENTO"].map(Sales_dic)
                                                                  #x recives eache line of proceduere(lambda x); acess the custos dic
                                                                  #with 2 keys (first is x(name os procedeure) and de secoind is 'CUSTO DIRETO')
                                                                  # IF OR ELSE TO VALIDATE IF THERE IS A VALUE FOR THOSE KEYS
  new_df['CUSTO DIRETO'] = new_df['PROCEDIMENTO PADRONIZADO'].map(lambda x: custos_dict[x]['CUSTO DIRETO'] if x in custos_dict else None)
  new_df['GRUPO'] = new_df["PROCEDIMENTO PADRONIZADO"].map(lambda x: custos_dict[x]["GRUPO"] if x in custos_dict else None)

  new_df['CUSTO DIRETO'] = new_df["CUSTO DIRETO"] * new_df["QUANTIDADE"]

  # Treating the financial values (/100)
  new_df['VALOR TABELA'] = new_df['VALOR TABELA'] / 100
  new_df['DISCONTO ITEM'] = new_df['DISCONTO ITEM'] / 100
  new_df['TOTAL DO ORÇAMENTO'] = new_df['TOTAL DO ORÇAMENTO'] / 100

  # Creating the column total Item :
  new_df["TOTAL ITEM"] = new_df['VALOR TABELA'] * new_df["QUANTIDADE"]

  #TRATING THE DATE VALUS
  new_df["DATA"] = pd.to_datetime(new_df["DATA"])

  #creating the month column
  new_df["MÊS"] = new_df["DATA"].dt.month
  new_df["MÊS"] = new_df["MÊS"].map(Month_dic)

  #Creating colums net total item
  new_df["TOTAL LÍQUIDO ITEM"] = new_df["TOTAL ITEM"] - new_df["DISCONTO ITEM"]

  # defining credit card costs, taxes and commissions

  taxes = 0.1425
  comission = 0.04
  credit_costs = 0.0818 #medain of 7 instalments
  other_costs = taxes + comission + credit_costs

  new_df["CUSTO TOTAL DIRETO ITEM"] = new_df["CUSTO DIRETO"] + (new_df["TOTAL ITEM"] * other_costs)
  new_df

  #reorganizing the columns:
  columns = ['ID CLIENTE','ID ORÇAMENTO','DATA',"MÊS",'UNIDADE',"GRUPO","PROCEDIMENTO","PROCEDIMENTO PADRONIZADO",
            'QUANTIDADE','VALOR TABELA','TOTAL ITEM','DISCONTO ITEM','TOTAL LÍQUIDO ITEM','CUSTO TOTAL DIRETO ITEM','TOTAL DO ORÇAMENTO',
            "CUSTO DIRETO",'FORMA DE PAGAMENTO','PARCELAS','PAGO?',"STATUS"]

  new_df = new_df[columns]

  return new_df

def bring_dictionaries():

  custos_dict = {
    "CARBOXITERAPIA": {"CUSTO DIRETO": 24.12, "GRUPO": "ESTÉTICA"},
    "CRIOLIPÓLISE": {"CUSTO DIRETO": 103.17, "GRUPO": "ESTÉTICA"},
    "DRENAGEM": {"CUSTO DIRETO": 28.91, "GRUPO": "ESTÉTICA"},
    "DRENAGEM 30 MIN": {"CUSTO DIRETO": 17.26, "GRUPO": "ESTÉTICA"},
    "HECCUS": {"CUSTO DIRETO": 21.60, "GRUPO": "ESTÉTICA"},
    "HIDRATAÇÃO": {"CUSTO DIRETO": 23.16, "GRUPO": "ESTÉTICA"},
    "LIMPEZA DE PELE": {"CUSTO DIRETO": 39.74, "GRUPO": "ESTÉTICA"},
    "PEELING DE DIAMANTE": {"CUSTO DIRETO": 32.71, "GRUPO": "ESTÉTICA"},
    "PRÓ- SHAPE": {"CUSTO DIRETO": 39.70, "GRUPO": "ESTÉTICA"},
    "PRÓ-SHAPE": {"CUSTO DIRETO": 39.70, "GRUPO": "ESTÉTICA"},
    "RADIOFREQUÊNCIA": {"CUSTO DIRETO": 28.65, "GRUPO": "ESTÉTICA"},
    "LAVIEEN": {"CUSTO DIRETO": 96.75, "GRUPO": "LAVIEEN"},
    "BOTOX LIGHT": {"CUSTO DIRETO": 162.46, "GRUPO": "MEDICINA ESTÉTICA"},
    "BOTOX POWER": {"CUSTO DIRETO": 307.82, "GRUPO": "MEDICINA ESTÉTICA"},
    "BUMBUM PERFEITO (40ml + 2 SESSÕES SCULPTRA)": {"CUSTO DIRETO": 10420.80, "GRUPO": "MEDICINA ESTÉTICA"},
    "CO2 CICATRIZ": {"CUSTO DIRETO": 189.24, "GRUPO": "MEDICINA ESTÉTICA"},
    "CO2 COLO": {"CUSTO DIRETO": 214.24, "GRUPO": "MEDICINA ESTÉTICA"},
    "CO2 MÃOS": {"CUSTO DIRETO": 189.24, "GRUPO": "MEDICINA ESTÉTICA"},
    "CO2 OLHEIRAS": {"CUSTO DIRETO": 189.24, "GRUPO": "MEDICINA ESTÉTICA"},
    "CO2 PESCOÇO": {"CUSTO DIRETO": 214.24, "GRUPO": "MEDICINA ESTÉTICA"},
    "CO2 ROSTO": {"CUSTO DIRETO": 249.24, "GRUPO": "MEDICINA ESTÉTICA"},
    "DERMAROLLER": {"CUSTO DIRETO": 115.48, "GRUPO": "MEDICINA ESTÉTICA"},
    "ENZIMA MELASMA": {"CUSTO DIRETO": 51.12, "GRUPO": "MEDICINA ESTÉTICA"},
    "GLÚTEO MAX": {"CUSTO DIRETO": 98.36, "GRUPO": "MEDICINA ESTÉTICA"},
    "PEELING QUÍMICO": {"CUSTO DIRETO": 31.34, "GRUPO": "MEDICINA ESTÉTICA"},
    "PREENCHIMENTO": {"CUSTO DIRETO": 297.80, "GRUPO": "MEDICINA ESTÉTICA"},
    "PREENCHIMENTO CORPORAL 2 ML": {"CUSTO DIRETO": 386.91, "GRUPO": "MEDICINA ESTÉTICA"},
    "PRÓ-BELLA": {"CUSTO DIRETO": 67.10, "GRUPO": "MEDICINA ESTÉTICA"},
    "PRÓ-CELL": {"CUSTO DIRETO": 39.55, "GRUPO": "MEDICINA ESTÉTICA"},
    "PRÓ-FIRM": {"CUSTO DIRETO": 53.17, "GRUPO": "MEDICINA ESTÉTICA"},
    "PRÓ-FIT": {"CUSTO DIRETO": 55.72, "GRUPO": "MEDICINA ESTÉTICA"},
    "PRÓ-LIPO": {"CUSTO DIRETO": 41.51, "GRUPO": "MEDICINA ESTÉTICA"},
    "PRÓ-MESO": {"CUSTO DIRETO": 45.82, "GRUPO": "MEDICINA ESTÉTICA"},
    "RADIESSE": {"CUSTO DIRETO": 771.18, "GRUPO": "MEDICINA ESTÉTICA"},
    "SCULPTRA": {"CUSTO DIRETO": 1034.18, "GRUPO": "MEDICINA ESTÉTICA"},
    "SECAGEM": {"CUSTO DIRETO": 22.50, "GRUPO": "MEDICINA ESTÉTICA"},
    "ULTRAFORMER BRAÇO": {"CUSTO DIRETO": 1018.12, "GRUPO": "ULTRAFORMER_III"},
    "ULTRAFORMER FULLFACE": {"CUSTO DIRETO": 735.62, "GRUPO": "ULTRAFORMER_III"},
    "ULTRAFORMER FULLFACE + PESCOÇO": {"CUSTO DIRETO": 1019.08, "GRUPO": "ULTRAFORMER_III"},
    "ULTRAFORMER FULLFACE + PESCOÇO + PAPADA": {"CUSTO DIRETO": 1258.12, "GRUPO": "ULTRAFORMER_III"},
    "ULTRAFORMER GLUTEO": {"CUSTO DIRETO": 913.12, "GRUPO": "ULTRAFORMER_III"},
    "ULTRAFORMER INTERNO COXA": {"CUSTO DIRETO": 1343.12, "GRUPO": "ULTRAFORMER_III"},
    "ULTRAFORMER MAÇA DO ROSTO": {"CUSTO DIRETO": 420.62, "GRUPO": "ULTRAFORMER_III"},
    "ULTRAFORMER OLHOS": {"CUSTO DIRETO": 243.12, "GRUPO": "ULTRAFORMER_III"},
    "ULTRAFORMER PAPADA": {"CUSTO DIRETO": 253.12, "GRUPO": "ULTRAFORMER_III"},
    "ULTRAFORMER PESCOÇO": {"CUSTO DIRETO": 463.12, "GRUPO": "ULTRAFORMER_III"},
    "PRÓ-SÉRUM": {"CUSTO DIRETO": 67.24, "GRUPO": "LAVIEEN"},
    "RETOQUE": {"CUSTO DIRETO": 0.0, "GRUPO": "MEDICINA ESTÉTICA"},
    "PREENCHIMENTO CORPORAL": {"CUSTO DIRETO": 386.91, "GRUPO": "MEDICINA ESTÉTICA"},
    "BUMBUM PERFEITO": {"CUSTO DIRETO": 9764.20, "GRUPO": "MEDICINA ESTÉTICA"},
    "UP BUMBUM": {"CUSTO DIRETO": 4882.10, "GRUPO": "MEDICINA ESTÉTICA"},
    "VALE PRESENTE": {"CUSTO DIRETO": 0.0, "GRUPO": "OUTROS"},
    "VICAE": {"CUSTO DIRETO": 56.60, "GRUPO": "MEDICINA ESTÉTICA"}

    }

  Appointments_dic = {
    "RADIOFREQUÊNCIA CORPORAL SESSÃO": "RADIOFREQUÊNCIA",
    "LIMPEZA DE PELE SESSÃO": "LIMPEZA DE PELE",
    "HECCUS / MANTHUS SESSÃO": "HECCUS",
    "DRENAGEM LINFÁTICA SESSÃO": "DRENAGEM",
    "BOTOX LIGHT (25 Unidades)": "BOTOX LIGHT",
    "BOTOX POWER (50 Unidades)": "BOTOX POWER",
    "PRÓ-SHAPE SESSÃO": "PRÓ- SHAPE",
    "PEELING QUÍMICO SESSÃO": "PEELING QUÍMICO",
    "DERMAROLLER ROSTO (Sessão)": "DERMAROLLER",
    "SECAGEM DE VASINHOS (SESSÃO) (EXCLUSIVO PARA AGENDAMENTO)": "SECAGEM",
    "RADIOFREQUÊNCIA SESSÃO CORTESIA": "RADIOFREQUÊNCIA",
    "CARBOXITERAPIA FACIAL SESSÃO": "CARBOXITERAPIA",
    "CARBOXITERAPIA CORPORAL SESSÃO": "CARBOXITERAPIA",
    "LIMPEZA DE PELE SESSÃO EXCLUSIVO R$ 50 (EXCLUSIVO PARA AGENDAMENTO)": "LIMPEZA DE PELE",
    "SCULPTRA 1 FRASCO": "SCULPTRA",
    "ENZIMAS PRÓ-MESO SESSÃO": "PRÓ-MESO",
    "MASSAGEM PRÓ-DETOX SESSÃO": "DRENAGEM",
    "RADIOFREQUÊNCIA FACIAL SESSÃO": "RADIOFREQUÊNCIA",
    "CO2 ROSTO (Sessão)": "CO2 ROSTO",
    "ENZIMAS PRÓ-FIT SESSÃO": "PRÓ-FIT",
    "PREENCHIMENTO 1ML": "PREENCHIMENTO",
    "HIDRATAÇÃO FACIAL RUBY SESSÃO": "HIDRATAÇÃO",
    "ENZIMAS PRÓ-LIPO SESSÃO": "PRÓ-LIPO",
    "PEELING DE DIAMANTE SESSÃO": "PEELING DE DIAMANTE",
    "MASSAGEM PRÓ-DETOX SESSÃO CORTESIA": "DRENAGEM",
    "ENZIMAS PRÓ-FIRM SESSÃO": "PRÓ-FIRM",
    "PEELING DE DIAMANTE SESSÃO CORTESIA": "PEELING DE DIAMANTE",
    "CO2 COLO (Sessão)": "CO2 COLO",
    "RETOQUE TOXINA BOTULÍNICA": "RETOQUE",
    "LIMPEZA DE PELE SESSÃO CORTESIA": "LIMPEZA DE PELE",
    "DRENAGEM FACIAL SESSÃO (EXCLUSIVO PARA AGENDAMENTO)": "DRENAGEM",
    "HIDRATAÇÃO FACIAL PINK DIAMOND SESSÃO CORTESIA": "HIDRATAÇÃO",
    "HECCUS / MANTHUS SESSÃO CORTESIA": "HECCUS",
    "CO2 MÃOS (Sessão)": "CO2 MÃOS",
    "CO2 PESCOÇO (Sessão)": "CO2 PESCOÇO",
    "CO2 CICATRIZ (Sessão)": "CO2 CICATRIZ",
    "ENZIMAS PRÓ-CELL SESSÃO": "PRÓ-CELL",
    "ENZIMAS MELASMA SESSÃO": "ENZIMA MELASMA",
    "ENZIMAS PRÓ-BELLA SESSÃO": "PRÓ-BELLA",
    "CARBOXITERAPIA CORPORAL SESSÃO CORTESIA": "CARBOXITERAPIA",
    "PRÓ-SHAPE SESSÃO CORTESIA": "PRÓ- SHAPE",
    "Preenchimento 4ml (EXCLUSIVO PARA AGENDAMENTO)": "PREENCHIMENTO",
    "PRÓ-SKIN SESSÃO": "PREENCHIMENTO",
    "Preenchimento 2ml (EXCLUSIVO PARA AGENDAMENTO)": "PREENCHIMENTO",
    "SKINBOOSTER 2ML (DESATIVADO)": "PREENCHIMENTO",
    "Preenchimento 3ml (EXCLUSIVO PARA AGENDAMENTO)": "PREENCHIMENTO",
    "HIDRATAÇÃO FACIAL PINK DIAMOND SESSÃO": "HIDRATAÇÃO",
    "CO2 OLHEIRAS (Sessão)": "CO2 OLHEIRAS",
    "ENZIMAS MELASMA 4 SESSÕES [COMBO PARA MANCHAS]": "ENZIMA MELASMA",
    "CRIOLIPÓLISE (2 ÁREAS) (EXCLUSIVO PARA AGENDAMENTO)": "CRIOLIPÓLISE",
    "SKINBOOSTER 1ML (DESATIVADO)": "PREENCHIMENTO",
    "CRIOLIPÓLISE (1 ÁREA)": "CRIOLIPÓLISE",
    "LIMPEZA DE PELE SESSÃO EXCLUSIVO R$ 90": "LIMPEZA DE PELE",
    "PEELING QUÍMICO FACIAL SIMPLES SESSÃO (EXCLUSIVO PARA AGENDAMENTO) DESATIVADO": "PEELING QUÍMICO",
    "PEELING QUÍMICO CORPORAL SESSÃO (EXCLUSIVO PARA AGENDAMENTO) DESATIVADO": "PEELING QUÍMICO",
    "ULTRAFORMER INTERNO COXA (Sessão)": "ULTRAFORMER INTERNO COXA",
    "ULTRAFORMER MAÇÃ DO ROSTO (Sessão)": "ULTRAFORMER MAÇA DO ROSTO",
    "ULTRAFORMER FULLFACE (Sessão)": "ULTRAFORMER FULLFACE",
    "MASSAGEM PRÓ-DETOX 5 SESSÕES [COMBO GORDURA LOCALIZADA]": "DRENAGEM",
    "LIMPEZA DE PELE SESSÃO CORTESIA INDIQUE": "LIMPEZA DE PELE",
    "ULTRAFORMER FULLFACE + PESCOÇO (Sessão)": "ULTRAFORMER FULLFACE + PESCOÇO",
    "ULTRAFORMER PESCOÇO (Sessão)": "ULTRAFORMER PESCOÇO",
    "ULTRAFORMER PAPADA (Sessão)": "ULTRAFORMER PAPADA",
    "PREENCHIMENTO 1ML VOLYME / DEFYNE": "PREENCHIMENTO",
    "BOTOX EM DOBRO (100 Unidades)": "BOTOX POWER",
    "ENZIMAS PRÓ-LIPO SESSÃO (DESATIVADO)": "PRÓ-LIPO",
    "ULTRAFORMER OLHOS (Sessão)": "ULTRAFORMER OLHOS",
    "ENZIMAS PRÓ-CELL SESSÃO EXCLUSIVO PARA COLABORADOR": "PRÓ-CELL",
    "PREENCHIMENTO 4ML VOLYME / DEFYNE (EXCLUSIVO PARA AGENDAMENTO)": "PREENCHIMENTO",
    "CO2 ROSTO 3 SESSÕES [CRONOGRAMA DA PELE PERFEITA]": "CO2 ROSTO",
    "ULTRAFORMER GLUTEO (Sessão)": "ULTRAFORMER GLUTEO",
    "PREENCHIMENTO 3ML VOLYME / DEFYNE (EXCLUSIVO PARA AGENDAMENTO)": "PREENCHIMENTO",
    "ULTRAFORMER BRAÇO (Sessão)": "ULTRAFORMER BRAÇO",
    "HIDRATAÇÃO FACIAL PINK DIAMOND DE ANIVERSÁRIO": "HIDRATAÇÃO",
    "PREENCHIMENTO 2ML VOLYME / DEFYNE (EXCLUSIVO PARA AGENDAMENTO)": "PREENCHIMENTO",
    "SECAGEM DE VASINHOS (SESSÃO)": "SECAGEM",
    "ENZIMAS PRÓ-CELL SESSÃO (DESATIVADO)": "PRÓ-CELL",
    "DERMAROLLER ROSTO 3 SESSÕES [COMBO PELE RENOVADA]": "DERMAROLLER",
    "ENZIMAS PRÓ-FIT SESSÃO EXCLUSIVO PARA COLABORADOR": "PRÓ-FIT",
    "PRÓ-SHAPE 5 SESSÕES [COMBO BUMBUM PERFEITO]": "PRÓ- SHAPE",
    "ENZIMAS PRÓ-FIT SESSÃO (DESATIVADO)": "PRÓ-FIT",
    "ENZIMAS PRÓ-FIRM SESSÃO (DESATIVADO)": "PRÓ-FIRM",
    "CRIOLIPÓLISE 2 SESSÕES [COMBO GORDURA LOCALIZADA]": "CRIOLIPÓLISE",
    "PEELING QUÍMICO 3 SESSÕES [COMBO PELE RENOVADA]": "PEELING QUÍMICO",
    "CRIOLIPÓLISE 2 SESSÕES [COMBO PRÓ-SLIM]": "CRIOLIPÓLISE",
    "LAVIEEN ROSTO COMPLETO SESSÃO (EXCLUSIVO PARA AGENDAMENTO)": "LAVIEEN",
    "LAVIEEN CORPORAL S": "LAVIEEN",
    "LAVIEEN BB LASER SESSÃO (EXCLUSIVO PARA AGENDAMENTO)": "LAVIEEN",
    "LAVIEEN ROSTO COMPLETO SESSÃO": "LAVIEEN",
    "LAVIEEN CORPORAL SESSÃO": "LAVIEEN",
    "ENZIMAS CAPILAR SESSÃO": "PRÓ-MESO",
    "ENZIMAS DE GORDURA DE PAPADA/AXILAR SESSÃO": "PRÓ-BELLA",
    "ENZIMAS DE GORDURA SESSÃO": "PRÓ-LIPO",
    "ENZIMAS PRÓ-FIRM SESSÃO (EXCLUSIVO PARA AGENDAMENTO)": "ENZIMA MELASMA",
    "ENZIMAS DE MELASMA SESSÃO": "ENZIMA MELASMA",
    "ENZIMAS PRÓ-FIT SESSÃO (EXCLUSIVO PARA AGENDAMENTO)": "PRÓ-FIT",
    "ENZIMAS PRÓ-CELL SESSÃO (EXCLUSIVO PARA AGENDAMENTO)": "PRÓ-CELL",
    "PRÓ-SKIN SESSÃO (EXCLUSIVO PARA AGENDAMENTO)": "PREENCHIMENTO",
    "LAVIEEN ROSTO SESSÃO CORTESIA": "LAVIEEN",
    "MASSAGEM MODELADORA/DRENAGEM LINFÁTICA SESSÃO (1H)": "DRENAGEM",
    "LIMPEZA DE PELE SESSÃO EXCLUSIVO R$ 50": "LIMPEZA DE PELE",
    "MASSAGEM MODELADORA/DRENAGEM LINFÁTICA SESSÃO (30 MIN)": "DRENAGEM (30 MIN)",
    "MASSAGEM MODELADORA/DRENAGEM LINFÁTICA SESSÃO CORTESIA (30MIN)": "DRENAGEM (30 MIN)",
    "RADIESSE 1 FRASCO": "RADIESSE",
    "LAVIEEN BB LASER SESSÃO": "LAVIEEN",
    "CO2 CICATRIZ (Sessão) (EXCLUSIVO PARA AGENDAMENTO)": "CO2 CICATRIZ",
    "CO2 COLO (Sessão) (EXCLUSIVO PARA AGENDAMENTO)": "CO2 COLO",
    "CO2 ROSTO (Sessão) (EXCLUSIVO PARA AGENDAMENTO)": "CO2 ROSTO",
    "CO2 OLHEIRAS (Sessão) (EXCLUSIVO PARA AGENDAMENTO)": "CO2 OLHEIRAS",
    "CO2 PESCOÇO (Sessão) (EXCLUSIVO PARA AGENDAMENTO)": "CO2 PESCOÇO",
    "CO2 ROSTO 3 SESSÕES [CRONOGRAMA DA PELE PERFEITA] (EXCLUSIVO PARA AGENDAMENTO)": "CO2 ROSTO",
    "ULTRAFORMER FULLFACE + PESCOÇO + PAPADA (Sessão) (Exclusivo para Agendamento)": "ULTRAFORMER FULLFACE + PESCOÇO + PAPADA",
    "CO2 MÃOS (Sessão) (EXCLUSIVO PARA AGENDAMENTO)": "CO2 MÃOS",
    "CRIOLIPÓLISE (2 ÁREAS)": "CRIOLIPÓLISE",
    "LAVIEEN ( 1 SESSÃO) [BELEZA EM DOBRO] (Exclusivo para Agendamento)": "LAVIEEN",
    "CRIOLIPÓLISE (1 ÁREA) [BELEZA EM DOBRO] (Exclusivo para Agendamento": "CRIOLIPÓLISE",
    "MASSAGEM MODELADORA/DRENAGEM LINFÁTICA SESSÃO (1H) [BELEZA EM DOBRO] (Exclusivo para Agendamento)": "DRENAGEM",
    "PEELING QUÍMICO 3 SESSÕES [CRONOGRAMA DA PELE PERFEITA]": "PEELING QUÍMICO",
    "LAVIEEN OLHOS SESSÃO (EXCLUSIVO PARA AGENDAMENTO)": "LAVIEEN",
    "ULTRAFORMER FULLFACE + PESCOÇO + PAPADA (Sessão)": "ULTRAFORMER FULLFACE + PESCOÇO + PAPADA",
    "MASSAGEM MODELADORA/DRENAGEM LINFÁTICA SESSÃO (1H)": "DRENAGEM",
    "MASSAGEM MODELADORA/DRENAGEM LINFÁTICA SESSÃO CORTESIA (30MIN)": "DRENAGEM (30 MIN)",
    "MASSAGEM MODELADORA/DRENAGEM LINFÁTICA SESSÃO (30 MIN)": "DRENAGEM (30 MIN)",
    "LAVIEEN ROSTO COMPLETO SESSÃO": "LAVIEEN",
    "PRÓ-SHAPE SESSÃO (PACOTE 10 SESSÕES)": "PRÓ- SHAPE",
    "MASSAGEM MODELADORA/DRENAGEM LINFÁTICA SESSÃO (1H) (PACOTE 10 SESSÕES)": "DRENAGEM",
    "PEELING DE DIAMANTE SESSÃO CORTESIA": "PEELING DE DIAMANTE",
    "HIDRATAÇÃO FACIAL PINK DIAMOND SESSÃO CORTESIA": "HIDRATAÇÃO",
    "RETORNO INJETÁVEIS E INVASIVOS": "UNMAPPED",
    "LAVIEEN ROSTO SESSÃO CORTESIA": "LAVIEEN",
    "LAVIEEN CORPORAL SESSÃO": "LAVIEEN",
    "LAVIEEN (PACOTE 3 SESSÕES)": "LAVIEEN",
    "PRÓ-SHAPE SESSÃO": "PRÓ- SHAPE",
    "CARBOXITERAPIA CORPORAL SESSÃO": "CARBOXITERAPIA",
    "LIMPEZA DE PELE SESSÃO EXCLUSIVO R$ 90": "LIMPEZA DE PELE",
    "HECCUS / MANTHUS SESSÃO": "HECCUS",
    "DERMAROLLER ROSTO (Sessão)": "DERMAROLLER",
    "ENZIMAS DE GORDURA SESSÃO": "PRÓ-LIPO",
    "HECCUS / MANTHUS SESSÃO CORTESIA": "HECCUS",
    "PEELING QUÍMICO SESSÃO": "PEELING QUÍMICO",
    "HECCUS / MANTHUS SESSÃO (PACOTE 10 SESSÕES)": "HECCUS",
    "ULTRAFORMER FULLFACE (Sessão)": "ULTRAFORMER FULLFACE",
    "ULTRAFORMER PAPADA (Sessão)": "ULTRAFORMER PAPADA",
    "ULTRAFORMER PESCOÇO (Sessão)": "ULTRAFORMER PESCOÇO",
    "CARBOXITERAPIA CORPORAL SESSÃO (PACOTE 10 SESSÕES)": "CARBOXITERAPIA",
    "CO2 CICATRIZ (Sessão) (JARDINS)": "CO2 CICATRIZ",
    "RETOQUE TOXINA BOTULÍNICA": "RETOQUE",
    "ULTRAFORMER MAÇÃ DO ROSTO (Sessão)": "ULTRAFORMER MAÇA DO ROSTO",
    "CO2 ROSTO (Sessão) (JARDINS)": "CO2 ROSTO",
    "LIMPEZA DE PELE SESSÃO CORTESIA": "LIMPEZA DE PELE",
    "HIDROLIPO SESSÃO (VILA MASCOTE)": "UNMAPPED",
    "LIMPEZA DE PELE SESSÃO EXCLUSIVO R$ 50 (EXCLUSIVO PARA AGENDAMENTO)": "LIMPEZA DE PELE",
    "BOTOX POWER (50 Unidades)": "BOTOX POWER",
    "ENZIMAS PRÓ-LIPO SESSÃO (DESATIVADO)": "PRÓ-LIPO",
    "CO2 PESCOÇO (Sessão) (JARDINS)": "CO2 PESCOÇO",
    "RADIOFREQUÊNCIA CORPORAL SESSÃO": "RADIOFREQUÊNCIA",
    "SECAGEM DE VASINHOS (SESSÃO)": "SECAGEM",
    "RADIOFREQUÊNCIA CORPORAL SESSÃO (PACOTE 10 SESSÕES)": "RADIOFREQUÊNCIA",
    "PREENCHIMENTO 1ML": "PREENCHIMENTO",
    "ENZIMA GLÚTEO MAX SESSÃO":"GLÚTEO MAX",
    "RADIOFREQUÊNCIA SESSÃO CORTESIA": "RADIOFREQUÊNCIA",
    "SCULPTRA 1 FRASCO": "SCULPTRA",
    "ULTRAFORMER INTERNO COXA (Sessão)": "ULTRAFORMER INTERNO COXA",
    "BOTOX LIGHT (25 Unidades)": "BOTOX LIGHT",
    "ENZIMAS CAPILAR SESSÃO": "PRÓ-MESO",
    "BOTOX POWER (50 Unidades) + LAVIEEN SESSÃO CORTESIA": "BOTOX POWER",
    "ENZIMAS GORDURA SESSÃO (VILA MASCOTE)": "PRÓ-LIPO",
    "Preenchimento 2ml (EXCLUSIVO PARA AGENDAMENTO)": "PREENCHIMENTO",
    "ULTRAFORMER OLHOS (Sessão)": "ULTRAFORMER OLHOS",
    "BUMBUM PERFEITO (40ml + 2 SESSÕES SCULPTRA)" : "BUMBUM PERFEITO",
    "UP BUMBUM (20ml + 1 SESSÃO SCULPTRA)" : "UP BUMBUM",
    "PREENCHIMENTO CORPORAL 2 ML" : "PREENCHIMENTO CORPORAL",
    "PRÓ-SERUM": "PRÓ-SÉRUM",
    "LAVIEEN ( 1 SESSÃO) [BELEZA EM DOBRO] (Exclusivo para Agendamento)": "LAVIEEN",
    "CO2 CICATRIZ (Sessão) (EXCLUSIVO PARA AGENDAMENTO)": "CO2 CICATRIZ",
    "LAVIEEN BB LASER SESSÃO (EXCLUSIVO PARA AGENDAMENTO)": "LAVIEEN",
    "CRIOLIPÓLISE (1 ÁREA) [BELEZA EM DOBRO] (Exclusivo para Agendamento": "CRIOLIPÓLISE",
    "CO2 MÃOS (Sessão) (EXCLUSIVO PARA AGENDAMENTO)": "CO2 MÃOS",
    "CO2 COLO (Sessão) (EXCLUSIVO PARA AGENDAMENTO)": "CO2 COLO",
    "PÓS TRATAMENTO": "PÓS TRATAMENTO",
    "BOTOX POWER (50 Unidades) + LAVIEEN SESSÃO CORTESIA": "BOTOX POWER",
    "PRÉ TRATAMENTO": "PRÉ TRATAMENTO",
    "ENZIMAS PRÓ-FIRM SESSÃO (EXCLUSIVO PARA AGENDAMENTO)": "ENZIMAS PRÓ-FIRM",
    "ULTRAFORMER FULLFACE + PESCOÇO + PAPADA (Sessão) (Exclusivo para Agendamento)": "ULTRAFORMER FULLFACE + PESCOÇO + PAPADA",
    "CO2 OLHEIRAS (Sessão) (EXCLUSIVO PARA AGENDAMENTO)": "CO2 OLHEIRAS",
    "MASSAGEM MODELADORA/DRENAGEM LINFÁTICA SESSÃO (1H) [BELEZA EM DOBRO] (Exclusivo para Agendamento)": "DRENAGEM",
    "LAVIEEN CORPORAL SESSÃO (EXCLUSIVO PARA AGENDAMENTO)": "LAVIEEN CORPORAL",
    "PREENCHIMENTO 3ML VOLYME / DEFYNE (EXCLUSIVO PARA AGENDAMENTO)": "PREENCHIMENTO",
    "CO2 PESCOÇO (Sessão) (EXCLUSIVO PARA AGENDAMENTO)": "CO2 PESCOÇO",
    "CO2 ROSTO 3 SESSÕES [CRONOGRAMA DA PELE PERFEITA] (EXCLUSIVO PARA AGENDAMENTO)": "CO2 ROSTO",
    "ROSTO FEMININO SESSÃO": "ROSTO FEMININO",
    "ENZIMAS PRÓ-CELL SESSÃO (EXCLUSIVO PARA AGENDAMENTO)": "ENZIMAS PRÓ-CELL",
    "CRIOLIPÓLISE (1 ÁREA) [BELEZA EM DOBRO] (Exclusivo para Agendamento)": "CRIOLIPÓLISE",
    "CO2 CICATRIZ (Sessão) (JARDINS)": "CO2 CICATRIZ",
    "CO2 ROSTO (Sessão) (JARDINS)": "CO2 ROSTO",
    "CO2 COLO (Sessão) (JARDINS)": "CO2 COLO",
    "CO2 MÃOS (Sessão) (JARDINS)": "CO2 MÃOS",
    "CO2 PESCOÇO (Sessão) (JARDINS)": "CO2 PESCOÇO",
    "CO2 OLHEIRAS (Sessão) (JARDINS)": "CO2 OLHEIRAS",
    "LAVIEEN CORPORAL\xa0SESSÃO": "LAVIEEN",
    "LAVIEEN OLHOS SESSÃO" : "LAVIEEN",
    "PEELING QUÍMICO 3 SESSÕES [DESCONTO PROGRESSIVO]" : "PEELING QUÍMICO"
   }



  Sales_dic = {
    "CRIOLIPÓLISE (1 ÁREA)": "CRIOLIPÓLISE",
    "LIMPEZA DE PELE SESSÃO EXCLUSIVO R$ 50 (EXCLUSIVO PARA AGENDAMENTO)": "LIMPEZA DE PELE",
    "LIMPEZA DE PELE SESSÃO CORTESIA": "LIMPEZA DE PELE",
    "PEELING DE DIAMANTE SESSÃO": "PEELING DE DIAMANTE",
    "LIMPEZA DE PELE SESSÃO EXCLUSIVO R$ 90": "LIMPEZA DE PELE",
    "Remoção de Tatuagem 1 a 35 cm²": "UNMAPPED",
    "BOTOX POWER (50 Unidades)": "BOTOX POWER",
    "PREENCHIMENTO 1ML": "PREENCHIMENTO",
    "BOTOX LIGHT (25 Unidades)": "BOTOX LIGHT",
    "SCULPTRA 1 FRASCO": "SCULPTRA",
    "CO2 CICATRIZ (Sessão)": "CO2 CICATRIZ",
    "PRÓ-SHAPE SESSÃO": "PRÓ- SHAPE",
    "ENZIMAS PRÓ-MESO SESSÃO": "PRÓ-MESO",
    "CO2 OLHEIRAS (Sessão)": "CO2 OLHEIRAS",
    "LIMPEZA DE PELE SESSÃO CORTESIA INDIQUE": "LIMPEZA DE PELE",
    "CARBOXITERAPIA CORPORAL SESSÃO": "CARBOXITERAPIA",
    "DRENAGEM LINFÁTICA SESSÃO": "DRENAGEM",
    "PEELING DE DIAMANTE SESSÃO CORTESIA": "PEELING DE DIAMANTE",
    "LUZ PULSADA SESSÃO": "UNMAPPED",
    "SECAGEM DE VASINHOS (SESSÃO) (EXCLUSIVO PARA AGENDAMENTO)": "SECAGEM",
    "PEELING QUÍMICO SESSÃO": "PEELING QUÍMICO",
    "ENZIMAS PRÓ-LIPO SESSÃO": "PRÓ-LIPO",
    "HECCUS / MANTHUS SESSÃO": "HECCUS",
    "Vale Presente": "UNMAPPED",
    "Vicae": "UNMAPPED",
    "MASSAGEM PRÓ-DETOX SESSÃO CORTESIA": "DRENAGEM",
    "HIDRATAÇÃO FACIAL PINK DIAMOND SESSÃO CORTESIA": "HIDRATAÇÃO",
    "CO2 ROSTO (Sessão)": "CO2 ROSTO",
    "ENZIMAS PRÓ-CELL SESSÃO": "PRÓ-CELL",
    "RADIOFREQUÊNCIA CORPORAL SESSÃO": "RADIOFREQUÊNCIA",
    "RADIOFREQUÊNCIA FACIAL SESSÃO": "RADIOFREQUÊNCIA",
    "MASSAGEM PRÓ-DETOX SESSÃO": "DRENAGEM",
    "ENZIMAS MELASMA SESSÃO": "ENZIMA MELASMA",
    "Preenchimento 2ml (EXCLUSIVO PARA AGENDAMENTO)": "PREENCHIMENTO",
    "PRÓ-SKIN SESSÃO": "PREENCHIMENTO",
    "ENZIMAS PRÓ-FIT SESSÃO": "PRÓ-FIT",
    "DERMAROLLER ROSTO (Sessão)": "DERMAROLLER",
    "ULTRAFORMER FULLFACE + PESCOÇO (Sessão)": "ULTRAFORMER FULLFACE + PESCOÇO",
    "LIMPEZA DE PELE SESSÃO": "LIMPEZA DE PELE",
    "ULTRAFORMER FULLFACE (Sessão)": "ULTRAFORMER FULLFACE",
    "ULTRAFORMER PAPADA (Sessão)": "ULTRAFORMER PAPADA",
    "CARBOXITERAPIA FACIAL SESSÃO": "CARBOXITERAPIA",
    "PREENCHIMENTO 1ML VOLYME / DEFYNE": "PREENCHIMENTO",
    "BOTOX EM DOBRO (100 Unidades)": "BOTOX POWER",
    "ENZIMAS PRÓ-BELLA SESSÃO": "PRÓ-BELLA",
    "Preenchimento 3ml (EXCLUSIVO PARA AGENDAMENTO)": "PREENCHIMENTO",
    "CARBOXITERAPIA CORPORAL SESSÃO CORTESIA": "CARBOXITERAPIA",
    "ENZIMAS MELASMA 4 SESSÕES [COMBO PARA MANCHAS]": "ENZIMA MELASMA",
    "PEELING QUÍMICO 3 SESSÕES [COMBO PARA MANCHAS]": "PEELING QUÍMICO",
    "BIOIMPEDÂNCIA SESSÃO": "UNMAPPED",
    "CO2 COLO (Sessão)": "CO2 COLO",
    "PRÓ-SHAPE 5 SESSÕES [COMBO BUMBUM PERFEITO]": "PRÓ- SHAPE",
    "ENZIMAS PRÓ-CELL 5 SESSÕES [COMBO BUMBUM PERFEITO]": "PRÓ-CELL",
    "QUEIXO SESSÃO (EXCLUSIVO PARA AGENDAMENTO)": "UNMAPPED",
    "HIDRATAÇÃO FACIAL PINK DIAMOND SESSÃO": "HIDRATAÇÃO",
    "ULTRAFORMER OLHOS (Sessão)": "ULTRAFORMER OLHOS",
    "AXILAS SESSÃO": "UNMAPPED",
    "PERNAS COMPLETAS SESSÃO": "UNMAPPED",
    "VIRILHA COMPLETA SESSÃO": "UNMAPPED",
    "DERMAROLLER ROSTO 3 SESSÕES [COMBO PELE RENOVADA]": "DERMAROLLER",
    "SKINBOOSTER 1ML (EXCLUSIVO PARA AGENDAMENTO)": "PREENCHIMENTO",
    "ULTRAFORMER MAÇÃ DO ROSTO (Sessão)": "ULTRAFORMER MAÇA DO ROSTO",
    "HIDRATAÇÃO FACIAL RUBY SESSÃO": "HIDRATAÇÃO",
    "CO2 MÃOS (Sessão)": "CO2 MÃOS",
    "ULTRAFORMER PESCOÇO (Sessão)": "ULTRAFORMER PESCOÇO",
    "DRENAGEM FACIAL SESSÃO (EXCLUSIVO PARA AGENDAMENTO)": "DRENAGEM",
    "RADIOFREQUÊNCIA SESSÃO CORTESIA": "RADIOFREQUÊNCIA",
    "HECCUS / MANTHUS SESSÃO CORTESIA": "HECCUS",
    "ENZIMAS PRÓ-LIPO 5 SESSÕES [COMBO GORDURA LOCALIZADA]": "PRÓ-LIPO",
    "CRIOLIPÓLISE 2 SESSÕES [COMBO GORDURA LOCALIZADA]": "CRIOLIPÓLISE",
    "ANESTÉSICO TÓPICO": "UNMAPPED",
    "BIOIMPEDÂNCIA SESSÃO CORTESIA": "UNMAPPED",
    "PEELING QUÍMICO FACIAL SIMPLES SESSÃO (EXCLUSIVO PARA AGENDAMENTO)": "PEELING QUÍMICO",
    "ENZIMAS PRÓ-FIRM SESSÃO": "PRÓ-FIRM",
    "ULTRAFORMER BRAÇO (Sessão)": "ULTRAFORMER BRAÇO",
    "CO2 PESCOÇO (Sessão)": "CO2 PESCOÇO",
    "PEELING QUÍMICO CORPORAL SESSÃO (EXCLUSIVO PARA AGENDAMENTO)": "PEELING QUÍMICO",
    "CRIOLIPÓLISE (2 ÁREAS) (EXCLUSIVO PARA AGENDAMENTO)": "CRIOLIPÓLISE",
    "PREENCHIMENTO 4ML VOLYME / DEFYNE (EXCLUSIVO PARA AGENDAMENTO)": "PREENCHIMENTO",
    "PRÓ-SHAPE SESSÃO CORTESIA": "PRÓ- SHAPE",
    "ULTRAFORMER INTERNO COXA (Sessão)": "ULTRAFORMER INTERNO COXA",
    "MASSAGEM PRÓ-DETOX 5 SESSÕES [COMBO GORDURA LOCALIZADA]": "DRENAGEM",
    "ULTRAFORMER GLUTEO (Sessão)": "ULTRAFORMER GLUTEO",
    "SECAGEM DE VASINHOS (SESSÃO)": "SECAGEM",
    "1/2 BRAÇO SESSÃO": "UNMAPPED",
    "HIALURONIDASE": "UNMAPPED",
    "PREENCHIMENTO 2ML VOLYME / DEFYNE (EXCLUSIVO PARA AGENDAMENTO)": "PREENCHIMENTO",
    "PERIANAL SESSÃO": "UNMAPPED",
    "1/2 PERNA SESSÃO": "UNMAPPED",
    "SKINBOOSTER 1ML (DESATIVADO)": "PREENCHIMENTO",
    "PEELING QUÍMICO FACIAL SIMPLES SESSÃO (EXCLUSIVO PARA AGENDAMENTO) DESATIVADO": "PEELING QUÍMICO",
    "CO2 ROSTO 3 SESSÕES [CRONOGRAMA DA PELE PERFEITA]": "CO2 ROSTO",
    "Preenchimento 4ml (EXCLUSIVO PARA AGENDAMENTO)": "PREENCHIMENTO",
    "PEELING QUÍMICO 3 SESSÕES [COMBO PELE RENOVADA]": "PEELING QUÍMICO",
    "PEELING QUÍMICO 3 SESSÕES [DESCONTO PROGRESSIVO]": "PEELING QUÍMICO",
    "PEELING QUÍMICO 2 SESSÕES [DESCONTO PROGRESSIVO]": "PEELING QUÍMICO",
    "PEELING QUÍMICO 3 SESSÕES [CRONOGRAMA DA PELE PERFEITA]": "PEELING QUÍMICO",
    "LAVIEEN ROSTO COMPLETO SESSÃO": "LAVIEEN",
    "LAVIEEN BB LASER SESSÃO": "LAVIEEN",
    "LAVIEEN OLHOS SESSÃO": "LAVIEEN",
    "AXILAS SESSÃO CORTESIA": "UNMAPPED",
    "LAVIEEN CORPORAL SESSÃO": "LAVIEEN",
    "CRIOLIPÓLISE 2 SESSÕES [COMBO PRÓ-SLIM]": "CRIOLIPÓLISE",
    "BRAÇOS COMPLETOS SESSÃO": "UNMAPPED",
    "PERNAS COMPLETAS + AXILAS + VIRILHA (EXCLUSIVO PARA AGENDAMENTO)": "UNMAPPED",
    "BUÇO SESSÃO": "UNMAPPED",
    "1/2 ABDÔMEN SESSÃO": "UNMAPPED",
    "1/2 ROSTO SESSÃO": "UNMAPPED",
    "LAVIEEN ROSTO COMPLETO SESSÃO (EXCLUSIVO PARA AGENDAMENTO)": "LAVIEEN",
    "GLÚTEO SESSÃO": "UNMAPPED",
    "PEITO SESSÃO": "UNMAPPED",
    "ABDOMEN COMPLETO SESSÃO": "UNMAPPED",
    "PESCOÇO SESSÃO": "UNMAPPED",
    "VIRILHA CAVADA SESSÃO": "UNMAPPED",
    "ENZIMAS DE GORDURA DE PAPADA/AXILAR SESSÃO": "PRÓ-BELLA",
    "ENZIMAS DE GORDURA SESSÃO": "PRÓ-LIPO",
    "ENZIMAS CAPILAR SESSÃO": "PRÓ-MESO",
    "ENZIMAS PRÓ-FIT SESSÃO (EXCLUSIVO PARA AGENDAMENTO)": "PRÓ-FIT",
    "PRÓ-SKIN SESSÃO (EXCLUSIVO PARA AGENDAMENTO)": "PREENCHIMENTO",
    "LAVIEEN ROSTO SESSÃO CORTESIA": "LAVIEEN",
    "RADIESSE 1 FRASCO": "RADIESSE",
    "ENZIMAS DE MELASMA SESSÃO": "ENZIMA MELASMA",
    "MASSAGEM PRÓ-DETOX/DRENAGEM LINFÁTICA SESSÃO": "DRENAGEM",
    "MASSAGEM MODELADORA/DRENAGEM LINFÁTICA SESSÃO CORTESIA": "DRENAGEM",
    "ULTRAFORMER FULLFACE + PESCOÇO + PAPADA (Sessão)": "ULTRAFORMER FULLFACE + PESCOÇO + PAPADA",
    "BARBA COMPLETA SESSÃO": "UNMAPPED",
    "LIMPEZA DE PELE SESSÃO EXCLUSIVO R$ 50": "LIMPEZA DE PELE",
    "MASSAGEM MODELADORA/DRENAGEM LINFÁTICA SESSÃO (1H)": "DRENAGEM",
    "AREOLA MAMILO SESSÃO (EXCLUSIVO PARA AGENDAMENTO)": "UNMAPPED",
    "MASSAGEM MODELADORA/DRENAGEM LINFÁTICA SESSÃO (30 MIN)": "DRENAGEM 30 MIN",
    "MASSAGEM MODELADORA/DRENAGEM LINFÁTICA SESSÃO CORTESIA (30MIN)": "DRENAGEM 30 MIN",
    "CRIOLIPÓLISE (2 ÁREAS)": "CRIOLIPÓLISE",
    "LAVIEEN ( 1 SESSÃO) [BELEZA EM DOBRO]": "LAVIEEN",
    "MASSAGEM MODELADORA/DRENAGEM LINFÁTICA SESSÃO (1H) [BELEZA EM DOBRO]": "DRENAGEM",
    "CRIOLIPÓLISE (1 ÁREA) [BELEZA EM DOBRO]": "CRIOLIPÓLISE",
    "CO2 ROSTO (Sessão) (EXCLUSIVO PARA AGENDAMENTO)": "CO2 ROSTO",
    "MASSAGEM MODELADORA/DRENAGEM LINFÁTICA SESSÃO (1H) (PACOTE 10 SESSÕES)": "DRENAGEM",
    "LAVIEEN (PACOTE 3 SESSÕES)": "LAVIEEN",
    "PRÓ-SERUM": "PRÓ-SÉRUM",
    "ENZIMA GLÚTEO MAX SESSÃO": "GLÚTEO MAX",
    "RADIOFREQUÊNCIA CORPORAL SESSÃO (PACOTE 10 SESSÕES)": "RADIOFREQUÊNCIA",
    "CARBOXITERAPIA CORPORAL SESSÃO (PACOTE 10 SESSÕES)": "CARBOXITERAPIA",
    "HECCUS / MANTHUS SESSÃO (PACOTE 10 SESSÕES)": "HECCUS",
    "LAVIEEN CORPORAL\xa0SESSÃO": "LAVIEEN",
    "PRÓ-SHAPE SESSÃO (PACOTE 10 SESSÕES)": "PRÓ-SHAPE",
    "BUMBUM PERFEITO (40ml + 2 SESSÕES SCULPTRA)" : "BUMBUM PERFEITO",
    "UP BUMBUM (20ml + 1 SESSÃO SCULPTRA)" : "UP BUMBUM",
    "PREENCHIMENTO CORPORAL 2 ML" : "PREENCHIMENTO CORPORAL",
    "LAVIEEN CORPORAL\xa0SESSÃO": "LAVIEEN",
    "LAVIEEN OLHOS SESSÃO" : "LAVIEEN",
    "PEELING QUÍMICO 3 SESSÕES [DESCONTO PROGRESSIVO]" : "PEELING QUÍMICO",
    "BOTOX POWER (50 Unidades) + LAVIEEN SESSÃO CORTESIA": "BOTOX POWER",
    "CO2 CICATRIZ (Sessão) (EXCLUSIVO PARA AGENDAMENTO)": "CO2 CICATRIZ",
    "LAVIEEN ( 1 SESSÃO) [BELEZA EM DOBRO] (Exclusivo para Agendamento)": "LAVIEEN",
    "CRIOLIPÓLISE (1 ÁREA) [BELEZA EM DOBRO] (Exclusivo para Agendamento": "CRIOLIPÓLISE",
    "CO2 PESCOÇO (Sessão) (EXCLUSIVO PARA AGENDAMENTO)": "CO2 PESCOÇO",
    "CO2 COLO (Sessão) (EXCLUSIVO PARA AGENDAMENTO)": "CO2 COLO",
    "MASSAGEM MODELADORA/DRENAGEM LINFÁTICA SESSÃO (1H) [BELEZA EM DOBRO] (Exclusivo para Agendamento)": "DRENAGEM",
    "CO2 MÃOS (Sessão) (EXCLUSIVO PARA AGENDAMENTO)": "CO2 MÃOS",
    "CO2 OLHEIRAS (Sessão) (EXCLUSIVO PARA AGENDAMENTO)": "CO2 OLHEIRAS",
    "ENZIMAS PRÓ-FIRM SESSÃO (EXCLUSIVO PARA AGENDAMENTO)": "PRÓ-FIRM",
    "ENZIMAS PRÓ-CELL SESSÃO (EXCLUSIVO PARA AGENDAMENTO)": "PRÓ-CELL",
    "ULTRAFORMER FULLFACE + PESCOÇO + PAPADA (Sessão) (Exclusivo para Agendamento)": "ULTRAFORMER FULLFACE + PESCOÇO + PAPADA",
    "CRIOLIPÓLISE (1 ÁREA) [BELEZA EM DOBRO] (Exclusivo para Agendamento)": "CRIOLIPÓLISE",
    "CO2 ROSTO (Sessão) (JARDINS)": "CO2 ROSTO",
    "CO2 OLHEIRAS (Sessão) (JARDINS)": "CO2 OLHEIRAS",
    "CO2 CICATRIZ (Sessão) (JARDINS)": "CO2 CICATRIZ",
    "CO2 COLO (Sessão) (JARDINS)": "CO2 COLO",
    'CO2 MÃOS (Sessão) (JARDINS)': 'CO2 MÃOS',
    'CO2 PESCOÇO (Sessão) (JARDINS)': 'CO2 PESCOÇO',
    'Vale Presente' : 'VALE PRESNETE',
    'Vicae' : 'VICAE'
   }

  duration_dic = {
  'BOTOX LIGHT': '00:30:00',
  'BOTOX POWER': '00:30:00',
  'CARBOXITERAPIA': '00:30:00',
  'CO2 CICATRIZ': '00:10:00',
  'CO2 COLO': '00:20:00',
  'CO2 MÃOS': '00:10:00',
  'CO2 OLHEIRAS': '00:10:00',
  'CO2 PESCOÇO': '00:20:00',
  'CO2 ROSTO': '00:30:00',
  'CRIOLIPÓLISE': '01:00:00',
  'DERMAROLLER': '00:30:00',
  'DRENAGEM': '01:00:00',
  'DRENAGEM 30 MIN' : '00:30:00',
  'DRENAGEM (30 MIN)': '00:30:00',
  'ENZIMA MELASMA': '00:30:00',
  'ENZIMAS PRÓ-CELL': '00:15:00',
  'ENZIMAS PRÓ-FIRM': '00:15:00',
  'GLÚTEO MAX': '00:15:00',
  'HECCUS': '00:30:00',
  'HIDRATAÇÃO': '00:30:00',
  'LAVIEEN': '00:15:00',
  'LAVIEEN CORPORAL': '00:15:00',
  'LIMPEZA DE PELE': '01:00:00',
  'PEELING DE DIAMANTE': '00:30:00',
  'PEELING QUÍMICO': '00:30:00',
  'PREENCHIMENTO': '00:30:00',
  'PRÓ- SHAPE': '01:00:00',
  'PRÓ-BELLA': '00:30:00',
  'PRÓ-FIT': '00:15:00',
  'PRÓ-LIPO': '00:15:00',
  'PRÓ-MESO': '00:30:00',
  'PRÓ-SÉRUM': '00:05:00',
  'PÓS TRATAMENTO': '00:15:00',
  'RADIESSE': '00:30:00',
  'RADIOFREQUÊNCIA': '00:30:00',
  'RETOQUE': '00:15:00',
  'SCULPTRA': '00:30:00',
  'SECAGEM': '00:30:00',
  'ULTRAFORMER BRAÇO': '00:45:00',
  'ULTRAFORMER FULLFACE': '01:00:00',
  'ULTRAFORMER FULLFACE + PESCOÇO': '01:30:00',
  'ULTRAFORMER FULLFACE + PESCOÇO + PAPADA': '01:30:00',
  'ULTRAFORMER GLUTEO': '00:45:00',
  'ULTRAFORMER INTERNO COXA': '01:30:00',
  'ULTRAFORMER MAÇA DO ROSTO': '00:45:00',
  'ULTRAFORMER OLHOS': '00:30:00',
  'ULTRAFORMER PAPADA': '00:30:00',
  'ULTRAFORMER PESCOÇO': '00:40:00',
  'UP BUMBUM': '00:40:00',
  'BUMBUM PERFEITO (40ml + 2 SESSÕES SCULPTRA)': '01:30:00',
  'PREENCHIMENTO CORPORAL' : '00:30:00',
  'VICAE' : '00:00:00',
  'VALE PRESENTE' : '00:00:00'}

  Month_dic = {
    1: 'Janeiro',
    2: 'Fevereiro',
    3: 'Março',
    4: 'Abril',
    5: 'Maio',
    6: 'Junho',
    7: 'Julho',
    8: 'Agosto',
    9: 'Setembro',
    10: 'Outubro',
    11: 'Novembro',
    12: 'Dezembro'
}
  return custos_dict, Sales_dic, Appointments_dic, duration_dic, Month_dic
